### ISSUE TITLE
Redefinition of Lexer class.

### ISSUE THREAD

**Issue by SouravKB** [Genivia/RE-flex#162]
Generated code contains Lexer definition twice. Once in outfile and once in header-file.

**Comment by genivia-inc** [comment]
The header should be included in the main application and the outfile must be compiled separately and then linked. It's the same approach taken by Flex C++.
